package pdf

import (
	"bytes"
	"fmt"

	"campaign-analyzer/internal/dto"

	"github.com/jung-kurt/gofpdf"
)

type PDFService struct{}

func NewPDFService() *PDFService {
	return &PDFService{}
}

func (p *PDFService) GenerateAnalysisPDF(data dto.AnalysisExportData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.AddPage()

	// Header
	addHeader(pdf)

	// Campaign Info
	addSectionTitle(pdf, "Campaign Info")
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(0, 8, "Campaign: "+data.CampaignName)
	pdf.Ln(6)
	pdf.Cell(0, 8, "Platform: "+data.Platform)
	pdf.Ln(10)

	// Metrics Table
	addSectionTitle(pdf, "Performance Metrics")
	addMetricsTable(pdf, data)

	// Summary
	addSectionTitle(pdf, "Summary")
	addParagraph(pdf, data.Summary)

	// Issues
	addSectionTitle(pdf, "Issues")
	addList(pdf, data.Issues)

	// Recommendations
	addSectionTitle(pdf, "Recommendations")
	addList(pdf, data.Recommendations)

	// Priority Actions
	addSectionTitle(pdf, "Priority Actions")
	addList(pdf, data.PriorityActions)

	var buf bytes.Buffer
	err := pdf.Output(&buf)

	return buf.Bytes(), err
}

func addHeader(pdf *gofpdf.Fpdf) {
	pdf.SetFont("Arial", "B", 18)
	pdf.Cell(0, 10, "Campaign Analysis Report")

	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)
	pdf.Cell(0, 6, "Generated by AI Campaign Analyzer")

	pdf.Ln(10)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(8)
}

func addSectionTitle(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, title)
	pdf.Ln(6)
}

func addMetricsTable(pdf *gofpdf.Fpdf, data dto.AnalysisExportData) {
	pdf.SetFont("Arial", "B", 12)

	headers := []string{"Metric", "Value"}
	widths := []float64{80, 80}

	// Header row
	for i, h := range headers {
		pdf.CellFormat(widths[i], 8, h, "1", 0, "C", false, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Arial", "", 12)

	rows := [][]string{
		{"CTR", fmt.Sprintf("%.2f%%", data.CTR*100)},
		{"CPC", fmt.Sprintf("Rp %.0f", data.CPC)},
		{"CPA", fmt.Sprintf("Rp %.0f", data.CPA)},
	}

	for _, row := range rows {
		for i, col := range row {
			pdf.CellFormat(widths[i], 8, col, "1", 0, "L", false, 0, "")
		}
		pdf.Ln(-1)
	}

	pdf.Ln(8)
}

func addParagraph(pdf *gofpdf.Fpdf, text string) {
	if text == "" {
		text = "- No summary available"
	}

	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 6, text, "", "", false)
	pdf.Ln(4)
}

func addList(pdf *gofpdf.Fpdf, items []string) {
	pdf.SetFont("Arial", "", 12)

	if len(items) == 0 {
		pdf.Cell(0, 6, "- No data available")
		pdf.Ln(6)
		return
	}

	for i, item := range items {
		line := fmt.Sprintf("%d. %s", i+1, item)
		pdf.MultiCell(0, 6, line, "", "", false)
	}

	pdf.Ln(4)
}
